<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
//
        DB::table('users')->insert([
           [
               'name'=>'Ngô Chí Thành Đạt',
               'email'=>'dat3578@gmail.com',
               'phone'=>'0394480757',
               'address'=>'Bắc Ninh',
               'password'=>Hash::make('ngodat02'),
               'usertype'=>0,
           ],
            [
                'name'=>'Nguyễn Minh Hiệp',
                'email'=>'hiep@gmail.com',
                'phone'=>'0394480757',
                'address'=>'Hà Nội',
                'password'=>Hash::make('ngodat02'),
                'usertype'=>0,
            ],
            [
                'name'=>'Nguyễn Văn Lập',
                'email'=>'lap@gmail.com',
                'phone'=>'038479745',
                'address'=>'Hà Nội',
                'password'=>Hash::make('ngodat02'),
                'usertype'=>0,
            ],
            [
                'name'=>'Staff',
                'email'=>'staff@gmail.com',
                'phone'=>'0394480757',
                'address'=>'Bắc Ninh',
                'password'=>Hash::make('ngodat02'),
                'usertype'=>1,
            ],
        ]);

        DB::table('meals')->insert([
            [
                'id'=>1,
                'name'=>'Breakfast',
            ],
            [
                'id'=>2,
                'name'=>'Lunch',
            ],
            [
                'id'=>3,
                'name'=>'Dinner',
            ],
            [
                'id'=>4,
                'name'=>'Snacks',
            ],
        ]);

        DB::table('product_categories')->insert([
            [
                'id'=>1,
                'name'=>'Vietnamese',
            ],
            [
                'id'=>2,
                'name'=>'Chinese',
            ],
            [
                'id'=>3,
                'name'=>'Mexico',
            ],
            [
                'id'=>4,
                'name'=>'Korea',
            ],
        ]);

        DB::table('products')->insert([
            [
                'id'=>1,
                'meal_id'=>1,
                'product_categories_id'=>1,
                'restaurant_id'=>1,
                'name'=>'Dumplings',
                'price'=>10.00,
                'image'=>'product1_banhbao.jpg',
                'description'=>'Dumplings are a type of dough dish that surrounds the filling.',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>2,
                'meal_id'=>1,
                'product_categories_id'=>2,
                'restaurant_id'=>2,
                'name'=>'Fried noodles',
                'price'=>20.50,
                'image'=>'product2_mixao.jpg',
                'description'=>'Fried noodles is a rustic dish but very delicious and good health.',
                'qty'=>100,
                'rate'=>4.5,
            ],
            [
                'id'=>3,
                'meal_id'=>1,
                'product_categories_id'=>1,
                'restaurant_id'=>3,
                'name'=>'Noodles',
                'price'=>50.00,
                'image'=>'product3_hutieu.jpg',
                'description'=>'Noodles is a traditional Vietnamese dish and it delicious and amazing.',
                'qty'=>20,
                'rate'=>4.0,
            ],
            [
                'id'=>4,
                'meal_id'=>2,
                'product_categories_id'=>1,
                'restaurant_id'=>1,
                'name'=>'Fried rice',
                'price'=>35.00,
                'image'=>'product4_comrang.jpg',
                'description'=>'Fried rice is a simple dish that is especially chosen by many people.',
                'qty'=>20,
                'rate'=>4.5,
            ],
            [
                'id'=>5,
                'meal_id'=>2,
                'product_categories_id'=>2,
                'restaurant_id'=>1,
                'name'=>'Broken rice',
                'price'=>10.00,
                'image'=>'product5_comtam.jpg',
                'description'=>'Broken rice is a popular dish of poor farmers and workers,it very good.',
                'qty'=>200,
                'rate'=>4.0,
            ],
            [
                'id'=>6,
                'meal_id'=>2,
                'product_categories_id'=>3,
                'restaurant_id'=>1,
                'name'=>'Fried pork',
                'price'=>10.00,
                'image'=>'product6_thitheoxao.jpg',
                'description'=>'Stir-fried pork is a nutritious and nutritious dish suitable for lunch.',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>7,
                'meal_id'=>2,
                'product_categories_id'=>1,
                'restaurant_id'=>2,
                'name'=>'Garlic fried fish',
                'price'=>5.00,
                'image'=>'product7_cachientoi.jpg',
                'description'=>'Garlic fried fish is a seafood dish that is fried with garlic which makes...',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>8,
                'meal_id'=>4,
                'product_categories_id'=>1,
                'restaurant_id'=>4,
                'name'=>'Fried beef',
                'price'=>10.00,
                'image'=>'product8_thitboxao.jpg',
                'description'=>'Fried beef is a rustic and nutritious dish for everyone, sports...',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>9,
                'meal_id'=>3,
                'product_categories_id'=>4,
                'restaurant_id'=>1,
                'name'=>'Steak',
                'price'=>100.00,
                'image'=>'product9_bitet.jpg',
                'description'=>'Steak is a dish consisting of flat slices of beef, usually grilled pan-fried.',
                'qty'=>200,
                'rate'=>4.0,
            ],
            [
                'id'=>10,
                'meal_id'=>1,
                'product_categories_id'=>3,
                'restaurant_id'=>2,
                'name'=>'Sandwiches',
                'price'=>18.00,
                'image'=>'product10_sandwiches.jpg',
                'description'=>'Sandwich is a food that usually consists of vegetables,placed of bread.',
                'qty'=>20,
                'rate'=>5.0,
            ],
            [
                'id'=>11,
                'meal_id'=>3,
                'product_categories_id'=>3,
                'restaurant_id'=>1,
                'name'=>'Grilled chicken',
                'price'=>9.00,
                'image'=>'product11_ganuongchao.jpg',
                'description'=>'Grilled chicken is a dish for the masses and it is delicious and easy to eat.',
                'qty'=>200,
                'rate'=>4.5,
            ],
            [
                'id'=>12,
                'meal_id'=>4,
                'product_categories_id'=>3,
                'restaurant_id'=>3,
                'name'=>'Custard cake',
                'price'=>19.00,
                'image'=>'product12_banhbonglan.jpg',
                'description'=>'Custard cake cake is a snack for those who like to eat fast and clean.',
                'qty'=>20,
                'rate'=>4.5,
            ],
            [
                'id'=>13,
                'meal_id'=>1,
                'product_categories_id'=>1,
                'restaurant_id'=>2,
                'name'=>'Pancakes',
                'price'=>7.00,
                'image'=>'product13_banhxeo.jpg',
                'description'=>'Pancakes are delicious snacks that are well received by many students...',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>14,
                'meal_id'=>4,
                'product_categories_id'=>1,
                'restaurant_id'=>4,
                'name'=>'Chicken feet',
                'price'=>10.00,
                'image'=>'product14_changa.jpg',
                'description'=>'Chicken feet is a snack that is worth eating it easy to eat and very delicious.',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>15,
                'meal_id'=>2,
                'product_categories_id'=>2,
                'restaurant_id'=>2,
                'name'=>'Chicken frequency',
                'price'=>12.00,
                'image'=>'product15_gatan.jpg',
                'description'=>'Chicken a very nutritious dish of the Chinese people,very for health.',
                'qty'=>200,
                'rate'=>4.0,
            ],
            [
                'id'=>16,
                'meal_id'=>3,
                'product_categories_id'=>4,
                'restaurant_id'=>4,
                'name'=>'Sushi',
                'price'=>10.00,
                'image'=>'product16_sushi.jpg',
                'description'=>'Sushi is a Korean folk dish and it  like rice, easy to eat and great...',
                'qty'=>200,
                'rate'=>3.5,
            ],
            [
                'id'=>17,
                'meal_id'=>2,
                'product_categories_id'=>1,
                'restaurant_id'=>4,
                'name'=>'Pork ribs',
                'price'=>14.00,
                'image'=>'product17_suonheo.jpg',
                'description'=>'Pork ribs are very good dish,a very good and nutritious dish worth.',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>18,
                'meal_id'=>3,
                'product_categories_id'=>2,
                'restaurant_id'=>1,
                'name'=>'Grilled beef patties',
                'price'=>11.00,
                'image'=>'product18_chabonuong.jpg',
                'description'=>'Grilled beef rolls is a dish in the form of fragrant grilled pork rolls...',
                'qty'=>200,
                'rate'=>5.0,
            ],
            [
                'id'=>19,
                'meal_id'=>4,
                'product_categories_id'=>1,
                'restaurant_id'=>4,
                'name'=>'Fried meatballs',
                'price'=>2.00,
                'image'=>'product19_thitvienchien.jpg',
                'description'=>'Fried meatballs are snack-shaped snacks that are easy eat and delicious.',
                'qty'=>200,
                'rate'=>4.0,
            ],
            [
                'id'=>20,
                'meal_id'=>2,
                'product_categories_id'=>4,
                'restaurant_id'=>2,
                'name'=>'Stir-fried vegetable',
                'price'=>30.00,
                'image'=>'product20_rauxao.jpg',
                'description'=>'Stir-fried vegetables are a nutritious and fiber-rich dish for every meal.',
                'qty'=>200,
                'rate'=>4.5,
            ],
            [
                'id'=>21,
                'meal_id'=>4,
                'product_categories_id'=>4,
                'restaurant_id'=>4,
                'name'=>'Peanut icecream',
                'price'=>19.50,
                'image'=>'product21_kembodauphong.jpg',
                'description'=>'Peanut butter ice cream is an ice cream for every snack and hot weather.',
                'qty'=>200,
                'rate'=>5.0,
            ],
        ]);

        DB::table('restaurants')->insert([
            [
                'id'=>1,
                'name'=>'Sen restaurant',
                'images'=>'Restaurant4.jpg',
                'description'=>'Sen Restaurant, a modern Japanese restaurant, has been a mainstay in Sag Harbor, New York since 1994. Zagat raves, “strike sushi gold at this trendy Sag Harbor phenomenon serving superb, slightly modernized Japanese dishes.” The warm and richly textured dining room is illuminated by amber lighting and framed with copper-capped wood beams. Small wood tables and hand-painted, rock encrusted walls complete the peaceful and dynamic decor.',
                'address'=>'23 Main Street ,Sag Harbor, NY 11963',
                'phone'=>'(631) 725-1774',
            ],
            [
                'id'=>2,
                'name'=>'Saigon Kitchen Restaurant',
                'images'=>'Restaurant3.jpg',
                'description'=>'Saigon Kitchen Restaurant - Hotel Des Arts Saigon on the second floor of the hotel brings diners back to Indochinese street atmosphere in the past. Street kitchens where diners can directly watch Experienced chefs prepare.',
                'address'=>' 8 Nguyễn Bỉnh Khiêm, Đa Kao, Quận 1, TP HCM',
                'phone'=>'097 500 2288',
            ],
            [
                'id'=>3,
                'name'=>' Windsor Plaza Hotel',
                'images'=>'Restaurant2.jpg',
                'description'=>'Windsor Plaza Hotel is one of the most luxurious and classy 5-star seafood buffet restaurants in Ho Chi Minh City. With a modern restaurant space, along with fresh seafood, professional service attitude of staff has helped Windsor Plaza Hotel assert its position in this culinary world.',
                'address'=>'18 An Dương Vương, Quận 5, TP HCM',
                'phone'=>'028 3833 6688',
            ],
            [
                'id'=>4,
                'name'=>'The Log',
                'images'=>'Restaurant1.jpg',
                'description'=>'Located on the rooftop of GEM Center, The LOG restaurant is a unique destination nestled away from the hustle and bustle of the city. Luxurious space covered with warm deep wood interspersed with green patches of grass, The LOG is the place to end fully enjoy the quintessence of contemporary cuisine.',
                'address'=>'Nguyệt Cầu Tam Giang Yên Phong Bắc Ninh',
                'phone'=>'(+84) 394480757',
            ],
        ]);
    }
}
